#!/bin/bash

# Copyright 2017-2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause


build_distro_rfs_debian() {
    [ $DISTROTYPE = debian ] && [ -f $RFSDIR/etc/buildinfo ] && \
    log_mute echo "$RFSDIR already exists!" && exit 0
	rfs_umount "$RFSDIR"

    [ `whoami` = root ] && sudopt="" || sudopt=sudo

    fbprint_n "Generating rootfs: $RFSDIR"
    cd $FBDIR
    test -c $RFSDIR/dev/pts/ptmx && $sudopt umount $RFSDIR/dev/pts
    test -f $RFSDIR/proc/uptime && $sudopt umount $RFSDIR/proc
    [ -n "$RFSDIR" ] && $sudopt rm -rf $RFSDIR/*


    if [ -n "$DISTROVARIANT" -a "$DISTROVARIANT" = "base" ]; then
        PKGS=''
        NEWRFSDIR=$FBOUTDIR/rfs/rootfs_${DISTRIB_VERSION}_debian_base_arm64
        RFSCMD=$FBDIR/configs/debian/debian_base_arm64.sh
    else
		case "$MACHINE" in
			   imx8*|imx95*)    PKGS=("${ls_pkgs[@]}" "${imx_pkgs[@]}" "${gnome_pkgs[@]}"); log_mute echo gnome package ;;
			   imx9*)           PKGS=("${ls_pkgs[@]}" "${imx_pkgs[@]}"); log_mute echo imx package ;;
			   l*)  	        PKGS=("${ls_pkgs[@]}"); log_mute echo ls  package ;;
			   *)               PKGS=("${ls_pkgs[@]}" "${imx_pkgs[@]}"); log_mute echo imx package ;;
		esac
        NEWRFSDIR=$RFSDIR
        RFSCMD=$FBDIR/configs/debian/debian_server_arm64.sh
    fi
    [ -f $NEWRFSDIR/etc/buildinfo ] && log_mute echo "$NEWRFSDIR already exists!" && exit 0

    rm -rf $NEWRFSDIR && mkdir -p $NEWRFSDIR

    if [ -n "$CONFIG_RFS_GRADUAL" ]; then

		# construct basic rfs
		$sudopt bash $RFSCMD "$NEWRFSDIR"

        rfs_mount $NEWRFSDIR

        show_one_line $sudopt chroot $NEWRFSDIR apt-get update

        install_success=false
        MAX_RETRIES=3
        for ((attempt=1; attempt<=$MAX_RETRIES; attempt++)); do
            log_mute echo "Try to generate rootfs for the $attempt time..."
            if show_one_line $sudopt chroot $NEWRFSDIR apt-get install --no-install-recommends -y "${PKGS[@]}"; then
                install_success=true
                break
            else
                if [ $attempt -lt $MAX_RETRIES ]; then
                    sleep 5
                    show_one_line $sudopt chroot apt update --fix-missing > /dev/null 2>&1
                fi
            fi
        done
        if ! $install_success; then
            echo "Generating rootfs failed, please try again."
            exit 1
        fi


        # clean cached packages
        log_mute $sudopt chroot $NEWRFSDIR apt clean
        log_mute $sudopt chroot $NEWRFSDIR apt autoclean
        log_mute $sudopt chroot $NEWRFSDIR apt autoremove -y

        rfs_umount $NEWRFSDIR
	else
		$sudopt bash $RFSCMD "$NEWRFSDIR" "${PKGS[@]}"
	fi

    # change merge all PATH to the same
    PROFILE=$NEWRFSDIR/etc/profile
    if [ -f ${PROFILE} ]; then
        sed -i '5d' ${PROFILE}
        sed -i '5i \ \ PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games"' ${PROFILE}
        sed -i '7d' ${PROFILE}
        sed -i '7i \ \ PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games"' ${PROFILE}
    fi

    # add packages.technexion.gpg to rootfs
    KEYRINGS=$NEWRFSDIR/etc/apt/keyrings
    SOURCES_LIST=$NEWRFSDIR/etc/apt/sources.list.d
    if [[ ! -f ${SOURCES_LIST}/vizionsdk.list ]];then
        wget -qO- https://download.technexion.com/apt/technexion.asc | gpg --dearmor > packages.technexion.gpg
        sudo install -D -o root -g root -m 644 packages.technexion.gpg $KEYRINGS/packages.technexion.gpg
        sudo echo "deb [arch=arm64 signed-by=/etc/apt/keyrings/packages.technexion.gpg] https://download.technexion.com/apt/vizionsdk/ stable main" > $SOURCES_LIST/vizionsdk.list
        sudo echo "deb [arch=arm64 signed-by=/etc/apt/keyrings/packages.technexion.gpg] https://download.technexion.com/apt/vizionviewer/ stable main" >> $SOURCES_LIST/vizionsdk.list
        rm packages.technexion.gpg
        rfs_mount $NEWRFSDIR
        log_mute $sudopt chroot $NEWRFSDIR /bin/bash -c "apt-get update && apt-get install -y ${tn_pkgs[*]}"
        rfs_umount $NEWRFSDIR
    fi

    $sudopt bash $FBDIR/configs/debian/debian_post_config.sh "$NEWRFSDIR"

    if [ -z "$DISTROVARIANT" ] || [ "$DISTROVARIANT" != "base" ]; then
        ln -sf /lib/systemd/system/platcfg.service "$NEWRFSDIR"/etc/systemd/system/multi-user.target.wants/platcfg.service
    fi

    fbprint_d $NEWRFSDIR
}
