# [general]

machine=imx8mp-edm-g

UBOOT_CONFIG="edm-g-imx8mp_defconfig"

COMPOSITE_IMG1_FILE_sd="bsp/imx-mkimage/imx8mp-edm-g/flash.bin"

# distro boot script
distro_bootscript="bsp/u-boot/imx8mp-edm-g/imx8mp-edm-g_boot.scr"


# imx8mp-ddr4-evk.dtb for ddr4 rev-a3 board
# imx8mp-evk.dtb for lpddr4 rev-b2 board with sound-wm8960 codec
# imx8mp-evk-revb4.dtb for lpddr4 rev-b4 board with new sound-wm8962 codec
distroboot=\
'env exists fdtfile || setenv fdtfile imx8mp-edm-g-wb.dtb;'\
'env exists image || setenv image Image;'\
'env exists devpart_boot || setenv devpart_boot 1;'\
'env exists devpart_root || setenv devpart_root 3;'\
'part uuid $devtype $devnum:$devpart_root partuuidr;'\
'setenv bootargs console=ttymxc1,115200 root=PARTUUID=$partuuidr rw rootwait $othbootargs;'\
'ext4load mmc $mmcdev:$devpart_boot $fdt_addr $fdtfile;'\
'fdt addr ${fdt_addr}; '\
'fdt resize ${fdt_buffer}; '\
'setexpr fdtovaddr ${fdt_addr} + 0xF0000; '\
'for ov in ${dtoverlay}; do '\
'  echo Overlaying ${ov}...; '\
'  ext4load mmc ${mmcdev}:${devpart_boot} ${fdtovaddr} imx8mp-edm-g-${baseboard}-${ov}.dtbo && fdt apply ${fdtovaddr}; '\
'done; '\
'ext4load mmc $mmcdev:$devpart_boot $loadaddr $image;'\
'booti $loadaddr - $fdt_addr'
