# [general]

machine=imx95-edm

UBOOT_CONFIG="edm-imx95_defconfig"

COMPOSITE_IMG1_FILE_sd="bsp/imx-mkimage/imx95-edm/flash.bin"

# distro boot script
distro_bootscript="bsp/u-boot/imx95-edm/imx95-edm_boot.scr"

# set distro boot to generate boot.scr which is searched by u-boot automatically
distroboot=\
'env exists fdtfile || setenv fdtfile imx95-edm-evm.dtb;'\
'env exists image || setenv image Image;'\
'env exists devpart_boot || setenv devpart_boot 1;'\
'env exists devpart_root || setenv devpart_root 3;'\
'part uuid $devtype $devnum:$devpart_root partuuidr;'\
'setenv bootargs console=ttyLP0,115200 root=PARTUUID=$partuuidr rw rootwait $othbootargs;'\
'ext4load mmc $mmcdev:$devpart_boot $fdt_addr $fdtfile;'\
'fdt addr ${fdt_addr}; '\
'fdt resize ${fdt_buffer}; '\
'setexpr fdtovaddr ${fdt_addr} + 0xF0000; '\
'for ov in ${dtoverlay}; do '\
'  echo Overlaying ${ov}...; '\
'  ext4load mmc ${mmcdev}:${devpart_boot} ${fdtovaddr} imx95-edm-evm-${ov}.dtbo && fdt apply ${fdtovaddr}; '\
'done; '\
'ext4load mmc $mmcdev:$devpart_boot $loadaddr $image;'\
'booti $loadaddr - $fdt_addr'
