# [general]

machine=imx93-edm

UBOOT_CONFIG="edm-imx93_defconfig"

# BOARD_VARIANTS="a0 a1"

COMPOSITE_IMG1_FILE_sd="bsp/imx-mkimage/imx93-edm/flash.bin"


# distro boot script
distro_bootscript="bsp/u-boot/imx93-edm/imx93-edm_boot.scr"

distroboot=\
'env exists fdtfile || setenv fdtfile imx93-edm-wb.dtb;'\
'env exists image || setenv image Image;'\
'env exists devpart_boot || setenv devpart_boot 1;'\
'env exists devpart_root || setenv devpart_root 3;'\
'part uuid $devtype $devnum:$devpart_root partuuidr;'\
'setenv bootargs console=ttyLP0,115200 earlycon root=PARTUUID=$partuuidr rw rootwait $othbootargs;'\
'ext4load mmc $mmcdev:$devpart_boot $fdt_addr $fdtfile;'\
'fdt addr ${fdt_addr}; '\
'fdt resize ${fdt_buffer}; '\
'setexpr fdtovaddr ${fdt_addr} + 0xF0000; '\
'for ov in ${dtoverlay}; do '\
'  echo Overlaying ${ov}...; '\
'  ext4load mmc ${mmcdev}:${devpart_boot} ${fdtovaddr} imx93-edm-${baseboard}-${ov}.dtbo && fdt apply ${fdtovaddr}; '\
'done; '\
'ext4load mmc $mmcdev:$devpart_boot $loadaddr $image;'\
'booti $loadaddr - $fdt_addr'
